/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 pullup-transformed.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pullup-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bar.geometry} material={materials['C Iron Corroded Stained.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['default.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials['Rubber Grip 01_1.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['default.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials['Rubber Grip 01_1.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['D Rubber.003']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Extrude.geometry} material={materials['Iron Cast 01.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Extrude1.geometry} material={materials['Iron Cast 01.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Extrude1_2.geometry} material={materials['Iron Cast 01.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Extrude_2.geometry} material={materials['Iron Cast 01.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['R?volution3'].geometry} material={materials['Brushed Aluminum Black.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['R?volution5'].geometry} material={materials['Brushed Aluminum Black.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/pullup-transformed.glb')
